#!/bin/bash
#cd /usr/local/var/www/htdocs/sturgeon
NOW=`date +%s`
sed -E -i '' 's/BUILD_VERSION = .+;/BUILD_VERSION = '$NOW';/' js/main.js
git add js/main.js
sed -E -i '' 's/cssBust=.+"/cssBust='$NOW'"/' index.htm
git add index.htm
#git commit -m 'Automatically updated build version'
#git status
